site_name: Travelogue
markdown_extensions:
  - attr_list
  - md_in_html
extra_css:
  - stylesheets/gallery.css
theme:
  name: material
  language: ja
  features:
    - navigation.tabs
    - navigation.tabs.sticky
plugins:
  search:
    lang: 'ja'

